apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: {{ .Values.description }}
  labels:
    release.giantswarm.io/version: {{ .Values.releaseVersion }}
    giantswarm.io/cluster: {{ .Values.name }}
    cluster.x-k8s.io/cluster-name: {{ .Values.name }}
    giantswarm.io/organization: {{ .Values.organization }}
  name: {{ .Values.name }}
  namespace: org-{{ .Values.organization }}
spec:
  topology:
    class: {{ .Values.className }}
    version: {{ .Values.kubernetesVersion }}
    controlPlane:
      replicas: {{ .Values.controlPlane.replicas }}
      metadata:
        labels:
          cluster.x-k8s.io/cluster-name: {{ .Values.name }}
          giantswarm.io/cluster: {{ .Values.name }}
          giantswarm.io/organization: {{ .Values.organization }}
          release.giantswarm.io/version: {{ .Values.releaseVersion }}
    workers:
      machineDeployments:
      {{- range .Values.nodePools }}
      - class: {{ .class }}
        name: {{ .name }}
        replicas: {{ .replicas }}
        metadata:
          labels:
            cluster.x-k8s.io/cluster-name: {{ $.Values.name }}
            giantswarm.io/cluster: {{ $.Values.name }}
            giantswarm.io/organization: {{ $.Values.organization }}
            release.giantswarm.io/version: {{ $.Values.releaseVersion }}
      {{- end }}
