apiVersion: v1
kind: List
items:
- apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
  kind: KubeadmControlPlaneTemplate
  metadata:
    labels:
      {{- include "labels.common" . | nindent 6 }}
    name: {{ include "resource.default.name" . }}
    namespace: {{ .Release.Namespace }}
  spec:
    template:
      spec:
        kubeadmConfigSpec:
          clusterConfiguration:
            apiServer:
              extraArgs:
                cloud-provider: external
            controllerManager:
              extraArgs:
                cloud-provider: external
          initConfiguration:
            nodeRegistration:
              kubeletExtraArgs:
                cloud-provider: external
              name: '{{ `{{ local_hostname }}` }}'
          joinConfiguration:
            nodeRegistration:
              kubeletExtraArgs:
                cloud-provider: external
              name: '{{ `{{ local_hostname }}` }}'
          useExperimentalRetryJoin: true
        machineTemplate:
          infrastructureRef:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
            kind: OpenStackMachineTemplate
            name: {{ include "resource.default.name" . }}-{{ .Values.controlPlane.class }}
        version: {{ .Values.kubernetesVersion }}
{{- range .Values.nodeClasses }}
- apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
  kind: KubeadmConfigTemplate
  metadata:
    labels:
      {{- include "labels.common" $ | nindent 6 }}
    name: {{ include "resource.default.name" $ }}-{{ .name }}
    namespace: {{ $.Release.Namespace }}
  spec:
    template:
      spec:
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              node-labels: giantswarm.io/node-pool={{ .name }}
            name: '{{ `{{ local_hostname }}` }}'
{{- end }}
- apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: OpenStackClusterTemplate
  metadata:
    labels:
      {{- include "labels.common" . | nindent 6 }}
    name: {{ include "resource.default.name" . }}
    namespace: {{ .Release.Namespace }}
  spec:
    template:
      spec:
        cloudName: {{ .Values.cloudName }}
        identityRef:
          name: {{ .Values.cloudConfig }}
          kind: Secret
        managedAPIServerLoadBalancer: true
        managedSecurityGroups: true
        {{- if .Values.nodeCIDR }}
        nodeCidr: {{ .Values.nodeCIDR }}
        {{- end }}
        {{- if .Values.externalNetworkID }}
        externalNetworkId: {{ .Values.externalNetworkID }}
        {{- end }}
        {{- if .Values.dnsNameservers }}
        dnsNameservers:
        {{- range .Values.dnsNameservers }}
        - {{ . }}
        {{- end }}
        {{- end }}
{{- range .Values.nodeClasses }}
- apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: OpenStackMachineTemplate
  metadata:
    labels:
      {{- include "labels.common" $ | nindent 6 }}
    name: {{ include "resource.default.name" $ }}-{{ .name }}
    namespace: {{ $.Release.Namespace }}
  spec:
    template:
      spec:
        cloudName: {{ $.Values.cloudName }}
        flavor: {{ .machineFlavor }}
        identityRef:
          name: {{ $.Values.cloudConfig }}
          kind: Secret
        image: {{ include "imageName" $ }}
        {{- if $.Values.rootVolume.enabled }}
        rootVolume:
          sourceType: image
          diskSize: {{ .diskSize }}
          sourceUUID: {{ $.Values.rootVolume.sourceUUID }}
        {{- end }}
{{- end }}
- apiVersion: cluster.x-k8s.io/v1alpha4
  kind: ClusterClass
  metadata:
    labels:
      {{- include "labels.common" . | nindent 6 }}
    name: {{ include "resource.default.name" . }}
    namespace: {{ .Release.Namespace }}
  spec:
    controlPlane:
      ref:
        apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
        kind: KubeadmControlPlaneTemplate
        name: {{ include "resource.default.name" . }}
    workers:
      machineDeployments:
      {{- range .Values.nodeClasses }}
      - class: {{ .name }}
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
              kind: KubeadmConfigTemplate
              name: {{ include "resource.default.name" $ }}-{{ .name }}
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
              kind: OpenStackMachineTemplate
              name: {{ include "resource.default.name" $ }}-{{ .name }}
      {{- end }}
    infrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: OpenStackClusterTemplate
        name: {{ include "resource.default.name" . }}
- apiVersion: cluster.x-k8s.io/v1alpha4
  kind: Cluster
  metadata:
    annotations:
      cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
    labels:
      cluster-apps-operator.giantswarm.io/watching: ""
      {{- include "labels.common" . | nindent 6 }}
    name: {{ include "resource.default.name" . }}
    namespace: {{ .Release.Namespace }}
  spec:
    topology:
      class: {{ include "resource.default.name" . }}
      version: {{ .Values.kubernetesVersion }}
      controlPlane:
        replicas: {{ .Values.controlPlane.replicas }}
        metadata:
          labels:
            {{- include "labels.common" . | nindent 12 }}
      workers:
        machineDeployments:
        {{- range .Values.nodePools }}
        - class: {{ .class }}
          name: {{ .name }}
          replicas: {{ .replicas }}
          metadata:
            labels:
              machine-deployment.giantswarm.io/failure-domain: "{{ .failureDomain }}"
              {{- include "labels.common" $ | nindent 14 }}
        {{- end }}
