{{- range $name, $value := .Values.nodePools }}
{{- $c := (merge (dict "currentClass"  $value) $.Values) -}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "resource.default.name" $ }}
  revisionHistoryLimit: 0
  replicas: {{ $value.replicas }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        {{- include "labels.selector" $ | nindent 8 }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "resource.default.name" $ }}-{{ $name }}-{{- include "kubeadmConfigTemplateRevision" (merge (dict "pool" $value) $) }}
      clusterName: {{ include "resource.default.name" $ }}
      failureDomain: {{ $value.failureDomain | quote }}
      infrastructureRef:
        apiVersion: {{ include "infrastructureApiVersion" . }}
        kind: OpenStackMachineTemplate
        name: {{ include "resource.default.name" $ }}-{{ $value.class }}-{{ include "osmtRevisionByClass" $c }}
      version: {{ $.Values.kubernetesVersion }}
{{- end }}
