{{- range $name, $value := (merge .Values.nodeClasses (dict "control-plane" .Values.controlPlane)) }}
{{- $c := (merge (dict "currentClass"  $value) $.Values) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: OpenStackMachineTemplate
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}-{{ $name }}-{{ include "osmtRevision" $c }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      {{- include "osmtSpec" $c | nindent 6 }}
{{- end }}
