{{- range $name, $value := (merge .Values.nodeClasses (dict "control-plane" .Values.controlPlane)) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: OpenStackMachineTemplate
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}-{{ $name }}-{{ include "osmtRevision" (merge $.Values $value) }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      {{- include "osmtSpec" (merge $.Values $value) | nindent 6 -}}
{{- end }}
