{{- if .Values.registry.configure -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-registry-configuration 
data:
  registry-config.toml: {{ include "registrySecretContent" . | b64enc | quote }}
{{- end -}}


