baseDomain: test.gigantic.io
cloudConfig: cloud-config
cloudName: openstack
clusterDescription: description
clusterName: testwc
dnsNameservers:
- 1.1.1.1
- 8.8.8.8
externalNetworkID: external-network-id
kubernetesVersion: v1.22.9
kubernetesVersionImages:
  v1.22.9: "ubuntu-2004-kube-v1.22.9"
  v1.23.14: "ubuntu-2004-kube-v1.23.14"
  v1.24.8: "ubuntu-2004-kube-v1.24.8"
  v1.25.4: "ubuntu-2004-kube-v1.25.4"
managementCluster: testmc
nodeCIDR: 10.6.0.0/24
organization: testorg

oidc:
  enabled: true

bastion:
  diskSize: 10
  flavor: bastion-flavor
  bootFromVolume: true

controlPlane:
  availabilityZones:
  - az1
  - az2
  - az3
  diskSize: 20
  flavor: control-plane-flavor
  replicas: 3
  bootFromVolume: true

nodeClasses:
  default:
    diskSize: 30
    flavor: worker-flavor
    bootFromVolume: true

nodePools:
  worker:
    class: default
    failureDomain: az1
    replicas: 5
