baseDomain: test.gigantic.io
cloudConfig: cloud-config
cloudName: openstack
clusterDescription: description
clusterName: testwc
dnsNameservers:
- 1.1.1.1
- 8.8.8.8
externalNetworkID: external-network-id
kubernetesVersion: 1.20.9
managementCluster: testmc
nodeCIDR: 10.6.0.0/24
organization: testorg

oidc:
  enabled: true

bastion:
  diskSize: 10
  flavor: bastion-flavor
  image: bastion-image
  bootFromVolume: true

controlPlane:
  availabilityZones:
  - az1
  - az2
  - az3
  diskSize: 20
  flavor: control-plane-flavor
  image: control-plane-image
  replicas: 3
  bootFromVolume: true

nodeClasses:
  default:
    diskSize: 30
    image: worker-image
    flavor: worker-flavor
    bootFromVolume: true

nodePools:
  worker:
    class: default
    failureDomain: az1
    replicas: 5
